### ISSUE TITLE
Where can I find "environment.yaml" and "requirements.txt" file

### ISSUE THREAD

**Issue by WontaeaeKim** [davidserra9/namedcurves#2]
Thank you for your awesome work!

I`m trying to set the environment as your instruction.
However, I can not find "environment.yaml" and "requirements.txt" files in this git hub project.
Could you let me know where are "environment.yaml" and "requirements.txt" files.

**Comment by davidserra9** [comment]
Hi Wontae Kim,

Thank you for your interest and your excellent work at ECCV!

Since the acceptance of the NamedCurves paper, I’ve been quite busy, so the code is still a work in progress. However, I’ve updated the repository to include a requirements.txt file and revised the setup instructions to make getting started easier.

I've also added the NamedCurves results on the MIT5K dataset.

Hope this helps, and let me know if you run into any issues!

**Comment by WontaeaeKim** [comment]
Hi David Serrano-Lozano.
Thank you for the quick response. 
It's working well.
